##https://github.com/gregrickaby/nextjs-github-pages

name: Build And Deploy Storybook

on:
    push:
        branches: [main]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2
              with:
                  persist-credentials: false

            - name: Cache Node Modules 💾
              uses: actions/cache@v2
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            - name: Install, Test and Build 🔧
              uses: actions/setup-node@v1
              with:
                  node-version: "14.x"

            - run: yarn install

            - name: Test
              continue-on-error: true
              - run: yarn build-storybook-test
              - run: yarn test
                

            - run: yarn build-storybook
              env:
                  CI: true

            - name: Deploy 🚀
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{secrets.GITHUB_TOKEN}}
                  publish_dir: ./storybook-static
